-- Run this once in Supabase Dashboard -> SQL Editor.
-- The serverless function uses the service-role key and can insert despite RLS.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 100),
  email text not null check (char_length(email) between 3 and 254),
  phone text not null check (char_length(phone) between 1 and 40),
  project_type text not null check (char_length(project_type) between 1 and 100),
  message text not null check (char_length(message) between 1 and 4000),
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;

-- Signed-in users may see only their own requests. Inserts occur via the
-- serverless endpoint after token verification, not directly from the browser.
create policy "Users can read their own leads"
  on public.leads
  for select
  to authenticated
  using ((select auth.uid()) = user_id);
